// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgrjsJ4Atv3sDqshqVd1qEnJDGpuPVQ-o',
    appId: '1:585725147048:web:761438c6e2c44efcee8f9d',
    messagingSenderId: '585725147048',
    projectId: 'lecture-b58e7',
    authDomain: 'lecture-b58e7.firebaseapp.com',
    storageBucket: 'lecture-b58e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMIwQY3D_v0D2uEaq8E1CP1LUM_xN2Jl8',
    appId: '1:585725147048:android:a08e40f90bf0f157ee8f9d',
    messagingSenderId: '585725147048',
    projectId: 'lecture-b58e7',
    storageBucket: 'lecture-b58e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9i60ehkZCiEbmBMTIgsJGgjMHAha9QGs',
    appId: '1:585725147048:ios:65e3e06bf7001f2cee8f9d',
    messagingSenderId: '585725147048',
    projectId: 'lecture-b58e7',
    storageBucket: 'lecture-b58e7.appspot.com',
    iosBundleId: 'com.example.projectLec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9i60ehkZCiEbmBMTIgsJGgjMHAha9QGs',
    appId: '1:585725147048:ios:13bf3ab457757979ee8f9d',
    messagingSenderId: '585725147048',
    projectId: 'lecture-b58e7',
    storageBucket: 'lecture-b58e7.appspot.com',
    iosBundleId: 'com.example.projectLec.RunnerTests',
  );
}
